In [1]:
import numpy as np
import pandas as pd
import random



import os

In [2]:
df = pd.read_csv('train_dataset.csv')
print('共{}个用户，{}本图书，{}条记录'.format(max(df['user_id'])+1, max(df['item_id'])+1, len(df)))

共53424个用户，10000本图书，5869631条记录


In [3]:
df.head()

user_id  item_id
0        0      257
1        0      267
2        0     5555
3        0     3637
4        0     1795

## 数据预处理¶
构建Dataset类
构建负样本
划分测试集与验证集
构建对应的Dataloader

In [4]:
rows_count_per_id = df.groupby('user_id').size().reset_index(name='count')
rows_count_per_id['count'].min()

17

In [5]:
def get_sequence_and_next_value(data):
    window_size=10
    sequences = []
    next_values = []
    data=data.item_id.values
    
    for i in range(len(data) - window_size):
        sequence = data[i : i + window_size]
        next_value = data[i + window_size]
        sequences.append(sequence)
        next_values.append(next_value)
  
    # 生成的序列和对应值
    data = {
        'Sequence': sequences,
        'Next_Value': next_values
    }
    
    # 将数据转换为 DataFrame
    df = pd.DataFrame(data)
    
    return df
    

# 将数据转换为列表


In [6]:
x=df.groupby('user_id').apply(get_sequence_and_next_value)

In [39]:
x=x.reset_index(drop=True)

x=x.sample(n=30000)

In [44]:
X=x.Sequence.values
df=np.vstack(X)
df=pd.DataFrame(df)
Y=x.Next_Value.values

In [48]:
Y

array([5093,  358,   27, ...,  706,  458, 1853], dtype=int64)

In [ ]:
from pycaret.regression import *
s = setup( df, target=Y, session_id = 123)


In [ ]:
x.Sequence.values

In [25]:
df=np.vstack(X)

In [26]:
df=pd.DataFrame(df)

In [27]:
df

0     1     2     3     4     5     6     7     8     9
0         257   267  5555  3637  1795   866    46  2737  4690   237
1         267  5555  3637  1795   866    46  2737  4690   237  2062
2        5555  3637  1795   866    46  2737  4690   237  2062   915
3        3637  1795   866    46  2737  4690   237  2062   915  4613
4        1795   866    46  2737  4690   237  2062   915  4613   110
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
5335386  1589  2365   340  3076  6454  3343  8608   564   449   647
5335387  2365   340  3076  6454  3343  8608   564   449   647  1048
5335388   340  3076  6454  3343  8608   564   449   647  1048   293
5335389  3076  6454  3343  8608   564   449   647  1048   293   890
5335390  6454  3343  8608   564   449   647  1048   293   890   228

[5335391 rows x 10 columns]

In [14]:
import pandas as pd
import numpy as np

# 给定的数组
arr = [np.array([257, 267, 5555, 3637, 1795, 866, 46, 2737, 4690, 237]),
       np.array([267, 5555, 3637, 1795, 866, 46, 2737, 4690, 237, 2062]),
       np.array([5555, 3637, 1795, 866, 46, 2737, 4690, 237, 2062, 915])]

# 将数组转换为整体的矩阵
matrix = np.vstack(arr)

# 创建 DataFrame
df = pd.DataFrame(matrix)

# 打印结果
print(df)

      0     1     2     3     4     5     6     7     8     9
0   257   267  5555  3637  1795   866    46  2737  4690   237
1   267  5555  3637  1795   866    46  2737  4690   237  2062
2  5555  3637  1795   866    46  2737  4690   237  2062   915


In [7]:
dt = create_model('dt')

NameError: name 'create_model' is not defined

In [33]:
X

array([array([ 257,  267, 5555, 3637, 1795,  866,   46, 2737, 4690,  237],
             dtype=int64)                                                 ,
       array([ 267, 5555, 3637, 1795,  866,   46, 2737, 4690,  237, 2062],
             dtype=int64)                                                 ,
       array([5555, 3637, 1795,  866,   46, 2737, 4690,  237, 2062,  915],
             dtype=int64)                                                 ,
       ...,
       array([ 340, 3076, 6454, 3343, 8608,  564,  449,  647, 1048,  293],
             dtype=int64)                                                 ,
       array([3076, 6454, 3343, 8608,  564,  449,  647, 1048,  293,  890],
             dtype=int64)                                                 ,
       array([6454, 3343, 8608,  564,  449,  647, 1048,  293,  890,  228],
             dtype=int64)                                                 ],
      dtype=object)

In [34]:
Y

array([2062,  915, 4613, ...,  890,  228,  339], dtype=int64)